### PR TITLE
Merge upstream master fix

### PR DESCRIPTION
**Pull request by leftclickben**

### CODE REVIEW

**Comment by leftclickben** [comment]
See also #174 and #175

**Comment by leftclickben** [comment]
I've fixed the tests and with the `testing` profile in Travis, everything is green.  For the `wamcmis` profile there is an error related to cache and/or locale: https://travis-ci.org/wamuseum/providence/jobs/71267403

**Comment by leftclickben** [comment]
Well I'm confused...
- In upstream, both `--hostname` and `--setup` parameters are given to the call in `.travis.yml` to `caUtils install`.  See https://github.com/collectiveaccess/providence/blob/master/.travis.yml#L23
- However, only one of these parameters is used, according to the code here: https://github.com/collectiveaccess/providence/blob/master/support/bin/caUtils#L231
- So in this case, the `--hostname` parameter is used and the `--setup` parameter is ignored (because it comes first).  At least, that's what the code says.
- Running `caUtils` locally behaves consistently with this: specifying both parameters behaves the same as specifying only the first parameter.  If `--hostname` is first, the default `setup.php` is used.  If `--setup` is first, the `--hostname` is ignored, which means the `HTTP_HOST` server variable is faked according to the location of `setup.php`.
- In Travis, specifying both parameters causes the installation to fail while processing list items for `wamcmis` (error about "cache key should not be empty"), however it works for the `testing` profile.  See https://travis-ci.org/wamuseum/providence/builds/71276250.  This implies that the `--setup` parameter is being used.
- Both profiles can be installed locally without error.
- In Travis, removing the `--hostname` parameter causes the installation to fail immediately with "Configuration is not available", and therefore the tests fail because there is no database schema.  This affects both `testing` and `wamcmis` profiles.  See https://travis-ci.org/wamuseum/providence/builds/71278473.

Any ideas?

It seems that removing the `--hostname` parameter was a bad idea, however it's the only way to get the installer to work locally.

Presumably since, with both parameters specified, the `testing` profile installs and the `wamcmis` profile doesn't, there is a problem with the `wamcmis` profile.  However it can be installed locally.

_head scratch_

**Comment by leftclickben** [comment]
@kehh (previous comment)

**Comment by kehh** [comment]
I think setup.php-dist specifies the default locale to be en_US and this doesn't exist in the WAM profile. That probably causes the pain you have been experiencing? (it's trying to set the cache entry for a null locale.

**Comment by leftclickben** [comment]
Yeah right... that makes sense... I'm specifying `--setup=./tests/setup-tests.php` but that includes the root-level `setup.php` (not `setup.php-dist`).  In Travis, this is `.travis.setup.php`, which doesn't specify a locale and includes `setup.php-dist` which specifies `en_US`.  In my local environment I have a `setup.php` that specifies `en_AU`.  That's why it works locally but not in Travis.

So to fix this, we can either not run the tests in Travis with `wamcmis`, and use some other method of testing that the profile is installable; or we can specify `en_AU` as the default locale somewhere.

There is a setting here: https://github.com/collectiveaccess/providence/blob/master/app/conf/global.conf#L37 but it doesn't really help us.  It would have to be overridden in one of the `setup.php` layers...

**Comment by leftclickben** [comment]
PS The @ mention wasn't because I wanted to bug you to answer me at half past midnight :-) I just wasn't sure if you'd been notified of my previous comment

**Comment by kehh** [comment]
Seems fairly simple. I know it's 'special handling' but that should be ok.

``` bash
if [ "$PROFILE" = "wamcmis" ]; then
    sed -i.bak s/en_US/en_AU/g setup.php-dist
fi
```

Also I was already looking at https://github.com/wamuseum/providence/pull/176#issuecomment-121981697 when your two other comments came in ;)

And maybe you're right about not needing to check whether the profile is installable as we don't actually test anything specifically from that profile. Maybe the `ProfileSchemaTest` is sufficient?

**Comment by kehh** [comment]
OK now it installs but the tests are relying on data from the testing profile. I think you're right to test the profile in another way. Hohum.

**Comment by kehh** [comment]
Apologies for pushing to your branch ;) but I think this puts us back to where we were

**Comment by leftclickben** [comment]
Yeah I'd thought of the similar solution of inserting a `define()` call to the bottom of `setup-tests.php`, just before the `require setup.php-dist`.

But I agree that simply not testing the `wamcmis` profile is a better idea, especially if there are tests that rely on the `testing` profile (...)

I've confirmed that we're still passing in both `--hostname` and `--setup` parameters to the `caUtils` call (and still don't understand how that even works correctly given the code) and we're no longer redirecting the output to a log file (I think that's better, otherwise you can't see it in the Travis UI).

So I think this is ready to merge.  But I think we need to do some more actual application testing, what do you think?

**Comment by kehh** [comment]
Agree about the application testing - maybe at least try running an import, viewing and editing objects.

**Comment by leftclickben** [comment]
I think we need to develop a manual test script that we run through every time we merge in changes from upstream.  That way we can follow the exact same steps and be sure of the expected results.  So we should develop the script against the current version in staging and then run it against the upgraded version.  In terms of content yeah that's a good start.  Maybe specifically check things like multipart IDs, a cross-section of field types, and taxonomic hierarchies.

**Comment by leftclickben** [comment]
We have used the application running on this code base with WAM data in it, and have found a couple of issues.

Issue 1: Active Directory authentication adapter is broken.  Users can login but group/role syncing does not work.

Issue 2: Bulk database processing fails due to "no database connection", possibly related to the ElasticSearch search adapter.  This seems to be a deadlock or race condition style of problem, because it disappears when the debugger is in use.

So, questions...

Question 1: Are we happy we've found all the issues or is more testing required?  I've tested a bit more this morning and things seem to be generally working.  (Scripting it can be a task on its own)

Question 2: Should we merge this and then fix the issues in separate PRs or should we make it so that everything is working in this PR?

**Comment by kehh** [comment]
Hey different styling for travis. 

Just wondering if git bisect would be a good candidate to find where the 'no database connection' problem occurs? Otherwise yes Q1 I think we're good to go. and Q2 fix in separate PR's.

**Comment by leftclickben** [comment]
Yeah I'd also thought of using `git bisect` for the database connection issue, was talking to @rowead about that this morning.

Cool well as this is my branch I'll let you do the honours :-)

**Pull request merged**
