### PR TITLE
Profile update20141212

### PR DESCRIPTION
**Pull request by kehh**
Update to installation profile for EPS …
- Adding eventDate to EPS records and subtypes
- Adding new measurement types for history
- Removing unused settings from attributes that changed type
- Update to a suite of lists
  - Anthropology Classification
  - History Classification
  - AZ/TZ
    - Collection Method
  - Preparation Types
  - add occurrenceDetails to simpson and mdc object types
  - Removing taxonRank attribute - taxonRank is now this list item type of the name
  - Change renderer for associatedTaxa to lookup (horizontal hierarchy browser was running out of memory
  - Geological Context now line breaks after 1 element
  - Allow more than 1 recommendation on conservation records
  - Fix typo in StorageType
  - Adding scientific_name_editor to all scientific name types (ranks)
  - Adding additional donor information in the bundle display - includes address and biography between <more> tags
  - A number of fields from the history migration
  - Update ACL permissions for roles
  - Add role for new museum view
  - Add palaontology_display with fields in it for bulk editing

Minor profile tweaks …
- fix profile so that it is valid
- Also remove a number of permissions for ca_attribute_taxonRank as that is no longer used.
- Adding en_AU locale UI labels

### CODE REVIEW

**Comment by kehh** [comment]
Travis appears to be having trouble with this build - too many new terms in the profile.

**Comment by leftclickben** [comment]
We should probably fix the issue with Travis.  I see you've tried making it spit out something, but it doesn't seem to be doing that as Travis is still timing out.  I'd rather not merge it because it means all our builds will fail and we won't know when it "really" fails.

**Comment by leftclickben** [comment]
(You did just add over 100,000 lines to the XML file, apparently...)

**Comment by kehh** [comment]
I'm leaning towards stripping out all of the taxonomy terms that currently get loaded via imports:
- history and anthropology classification
- material types
- preparation types
- collecting methods

we have already strip out:
- chemical elements
- eps taxonomy
- geological formations
- host rock types
- minerals and 
- taxonomy

Using xslt's: https://github.com/wamuseum/cmis-tools/tree/master/xslt

Should make the installs a lot faster.

**Comment by leftclickben** [comment]
I'll leave that to you, but that should be a decision based on what you want and shouldn't be influenced by CI.  The problem with CI seems to be that there is no output -- if the timeout was longer, it would succeed.  So we should fix the problem by either introducing some output, or increasing the timeout (not really a fix though, because next time stuff is added to the profile it might break again).  Do you want me to look at the output problem?

**Comment by kehh** [comment]
No don't worry about the output. Ironically we (you) initially piped output to install.log because travis was complaining there was too much output and therefore failing. Don't worry about looking into the output problem.

**Comment by kehh** [comment]
oh and did I say, don't worry about looking at the output problem

**Comment by leftclickben** [comment]
I do vaguely recall something about too much output.  Hmmm.  Maybe we could just get it to output a dot for every line it would have output.. so there is still output so Travis knows something is still happening, but not so much that it complains about that (bloody picky).

Wait did you say to worry about the output problem or not? ;-P

**Pull request merged**
