### PR TITLE
Zoology collecting event fixes

### PR DESCRIPTION
**Pull request by kehh**
- Fixes for undefined variables
- Extend importer plugin to support ca_list_items (for controlled vocabulary metadata elements)
- Update installation profile
  don't merge this yet - just checking installation profile

### CODE REVIEW

**Comment by kehh** [comment]
ok this is ready to merge once the test pass

**Comment by leftclickben** [comment]
It just occurred to me that it should be quite easy to write unit tests for this, using the pattern I set up for the other plugins (with a database setup and automated teardown).  It's just data in, database lookup-and-possible-creation, and slightly modified data out.  It won't affect this merge but we (probably me) should do that today if possible.

**Comment by kehh** [comment]
Sounds great

**Comment by kehh** [comment]
I wanted to use a test to develop it  but just couldn't figure out how to start.

**Comment by leftclickben** [comment]
Be in soon, we can pair on it if you like, at least to a point where the tests are running and you understand how it works, maybe one happy path test and one sad path test.  Then I'll finish off the wider range of test cases so you can get on with the real work ;-)

**Comment by leftclickben** [comment]
These plugin tests do have a pretty specific structure, we can improve the documentation while we're at it.

**Pull request merged**
