### PR TITLE
Profile update 20150507

### LINKED ISSUE #167: Fix ci
https://travis-ci.org/wamuseum/providence
WA Museum fork: [Build Status](http://travis-ci.org/wamuseum/providence)

https://github.com/wamuseum/providence/compare/develop...kehh:profileUpdate20150507?expand=1

### PR DESCRIPTION
**Pull request by leftclickben**
Profile updates as described by commit messages.

Also fixes #167

### CODE REVIEW

**Comment by leftclickben** [comment]
I'm not sure who should merge this?

**Comment by kehh** [comment]
Well that looks you're happy enough with it. I'm mergeing it.

**Comment by leftclickben** [comment]
TBH, I couldn't and didn't look at the actual profile changes.  You're happy with the profile itself, and I'm happy now that the tests are running.

There is a follow-up that we need to do, which is to make this change of mine on whatever server the profile is coming from, otherwise the missing `value` will go missing again next time we run the update.

Also, I'm wondering how this happened?  I guess it was an accidental deletion via the UI?  Or possibly a problem because the value is `0` and therefore might look the same as `null` with coercion, somewhere?  (thanks php)

So I'll raise an issue / task to look at whether the value is missing on the source server, and take appropriate action depending on the result.

**Comment by kehh** [comment]
ok cool

**Pull request merged**
