### PR TITLE
WAMNH-162: Add plugin that supports duplication including invalid `idno` strings

### PR DESCRIPTION
**Pull request by kehh**
- Requiring valid idno means that duplication fails.
- iThis plugin takes the generated idno that comes out of the built in CA and applies replacement.
- actual configuration to come in a separate PR

### CODE REVIEW

**Comment by kehh** [comment]
Don't deploy this to UAT / production yet as there are migrations running on those servers that I don't want to interrupt.

**Comment by kehh** [comment]
This is copypasta of a previously reviewed plugin.

**Comment by leftclickben** [comment]
My only comment here is that unit tests for this would be easy to write (by the looks of it you don't need the database).

**Comment by kehh** [comment]
I'll add a task for that.

**Pull request merged**
