### PR TITLE
Release 1.5.wamuseum.1

### PR DESCRIPTION
**Pull request by leftclickben**

### CODE REVIEW

**Comment by kehh** [comment]
Hi Ben, 
As some of those tests are upstream would you like me to merge this then we fix those in a separate PR? 
K

**Comment by leftclickben** [comment]
We should fix the issue with the profile, and then merge, and then fix the other failing tests like http/https for wikipedia.

**Comment by kehh** [comment]
OK so we need to get the following tests passing:
- WamTitleGeneratorPluginIntegrationTest::testMatchingRecordWithSingleCollectionGeneratesCorrectTitle
- WamTitleGeneratorPluginIntegrationTest::testMatchingRecordWithMultipleCollectionsGeneratesCorrectTitle
  and 
- ProfileSchemaTest::testAvailableProfilesConformToSchema

**Comment by leftclickben** [comment]
The wikipedia tests are fixed in `master-fix`: https://github.com/collectiveaccess/providence/commit/ce9939fb33e041c035239b932df77f25801a827d

I've merged that in here because as discussed we should be following that branch anyway instead of the release branch.

The tests you listed are still failing as you predicted.  Others are passing.  https://travis-ci.org/leftclickben/providence/jobs/70365304

**Pull request closed without merging**
