### PR TITLE
Made a new label file

### PR DESCRIPTION
**Pull request by mostro20**
Not sure if this will properly work, am mostly running this as a test.

### CODE REVIEW

**Comment by kehh** [comment]
Thanks for this Morgan. Will try to review this tomorrow.

**Comment by mostro20** [comment]
Updated it slightly, just got the sizes a bit smaller.

**Comment by kehh** [comment]
I just noticed that you are doing this on a 'develop' branch. You should create a new 'branch' on your fork to do the label development work. (git checkout -b labelDevelopment) and then do pull requests to wamuseum/develop from mostro20/labelDevelopment.

The best example of this kind of workflow is https://guides.github.com/introduction/flow/index.html

**Comment by kehh** [comment]
Closing this and doing a new PR

**Pull request closed without merging**
