### PR TITLE
Update to installation profile to include object use history bundles and some invertebrate palaeo and

### PR DESCRIPTION
**Pull request by kehh**
Includes changes for the object use history bundle and fields for the invertebratePalaeontology schema
- loan_in_date added to cutodial loan
- Coorinate Uncertainty > Coordinate Uncertainty
- institutionId added to removed from occurrences
- anthropologyMaterialTypes no longer required
- identified by added to invertebrate_palaeontology objects
- determination metadata element for invert palaeo
- Object Use history:
  - Consistent accross the four UI's (Natural History, Anthropology, Minerals & Palaeontology)
  - remove storage locations and loans from the objects ui's (now done via the OUH bundle
  - Place UI - close hierarchy by default
  - Added UI for EPS Palaeontology
  - Fixes to logic of loans to entities relationships, now:
  - borrowed from <=> lent to
  - Added invertebrate palaeo and vertebrate_palaeo user groups
    @gissues:{"order":50,"status":"backlog"}

### CODE REVIEW

**Comment by leftclickben** [comment]
Actually checking your notes against what I actually did, one thing isn't true here: the storage locations and loans haven't been removed from all the UIs.  Specifically Anthropology and Minerals still have storage locations, I can't see any others.  I can make the change in the XML and push it back up (I've got it open right here) but then the change would also need to be made on the server so better it comes from that end.

**Comment by kehh** [comment]
OK just running a reexport. will update the PR when the profile's done. 
K

**Comment by kehh** [comment]
OK updated the profile with e6baf12. Should be good to go.

**Comment by kehh** [comment]
I have also added a task to youtrack to make the storage location display hierarchical in the object use history.

**Comment by leftclickben** [comment]
Yep looks good, will merge once Travis is done.

**Pull request merged**
